# Generated by Django 5.2.9 for KindEltern Web
# Initial migration for notifications app - Notification model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('karteien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='Auto-generated primary key.',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('PENDING_CREATED', 'New pending change'),
                            ('DECLINED_CREATED', 'Change declined'),
                            ('APPROVED', 'Change approved'),
                        ],
                        db_index=True,
                        help_text='Type of notification (PENDING_CREATED, DECLINED_CREATED).',
                        max_length=32,
                    ),
                ),
                (
                    'payload',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional data for the notification. Can include: '
                                  'family_id, parent_name, child_name, decline_reason, etc.',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='When the notification was created.',
                    ),
                ),
                (
                    'read_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='When the notification was marked as read. Null if unread.',
                        null=True,
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        help_text='User who receives this notification.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'record',
                    models.ForeignKey(
                        blank=True,
                        help_text='Reference to the KarteiRecord this notification is about. '
                                  'Null if notification is not about a specific record.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to='karteien.karteirecord',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['recipient', 'read_at'],
                name='notificatio_recipie_564b1f_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['recipient', 'type', 'read_at'],
                name='notificatio_recipie_d40dd9_idx',
            ),
        ),
    ]
