# Generated by Django 5.2.9 on 2025-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KarteiRecord",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="Unique record ID. Excel: AV (48), Access: ID field.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Year of the record (2024, 2025, etc.). Replaces separate yearly Access files.",
                    ),
                ),
                (
                    "family_id",
                    models.CharField(
                        db_index=True,
                        help_text="Family identifier. Excel: A (1), Access: Value1. Groups related records.",
                        max_length=50,
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Parent name (Eltern). Excel: B (2), Access: Value2.",
                        max_length=255,
                    ),
                ),
                (
                    "child_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Child name (Kind). Excel: D (4), Access: Value4.",
                        max_length=255,
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True,
                        help_text="Child's birthdate. Excel: E (5), Access: Value5.",
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Address. Excel: F (6), Access: Value6.",
                        max_length=500,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phone number (as text to preserve leading zeros). Excel: G (7), Access: Value7.",
                        max_length=50,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mobile number (as text). Excel: H (8), Access: Value8.",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email address. Excel: I (9), Access: Value9.",
                        max_length=255,
                    ),
                ),
                (
                    "subject1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary subject 1. Excel: J (10), Access: Value10.",
                        max_length=255,
                    ),
                ),
                (
                    "price1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for subject 1. Excel: M (13), Access: Value13.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "subject2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subject 2. Excel: O (15), Access: Value15.",
                        max_length=255,
                    ),
                ),
                (
                    "price2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for subject 2. Excel: R (18), Access: Value18.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "extra1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Extra subject 1. Excel: AK (37), Access: Value37.",
                        max_length=255,
                    ),
                ),
                (
                    "extra2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Extra subject 2. Excel: AL (38), Access: Value38.",
                        max_length=255,
                    ),
                ),
                (
                    "extra3",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Extra subject 3. Excel: AM (39), Access: Value39.",
                        max_length=255,
                    ),
                ),
                (
                    "month_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 1 value (January). Excel: U (21), Access: Value21.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 2 value (February). Excel: V (22), Access: Value22.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 3 value (March). Excel: W (23), Access: Value23.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 4 value (April). Excel: X (24), Access: Value24.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 5 value (May). Excel: Y (25), Access: Value25.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 6 value (June). Excel: Z (26), Access: Value26.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_7",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 7 value (July). Excel: AA (27), Access: Value27.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_8",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 8 value (August). Excel: AB (28), Access: Value28.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_9",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 9 value (September). Excel: AC (29), Access: Value29.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 10 value (October). Excel: AD (30), Access: Value30.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_11",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 11 value (November). Excel: AE (31), Access: Value31.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_12",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Month 12 value (December). Excel: AF (32), Access: Value32.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sepa_marker",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SEPA marker (e.g., 'SEPA'). Excel: AU (47), Access: Value47. Rows with SEPA have restrictions for Operator role.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "Normal"),
                            ("PENDING", "Pending Approval"),
                            ("DECLINED", "Declined"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Record status: '', 'PENDING', or 'DECLINED'. Excel: BA (53). Derived from presence in pre_tblKartei/decl_tblKartei.",
                        max_length=20,
                    ),
                ),
                (
                    "last_change_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Admin", "Admin"),
                            ("Operator", "Operator"),
                            ("Superadmin", "Superadmin"),
                        ],
                        default="",
                        help_text="Role of user who made last change. Excel: AW (49), Access: Value49.",
                        max_length=20,
                    ),
                ),
                (
                    "last_change_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last sync/change. Excel: AX (50), Access: Value50.",
                        null=True,
                    ),
                ),
                (
                    "last_change_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time of last sync/change. Excel: AY (51), Access: Value51.",
                        null=True,
                    ),
                ),
                (
                    "history_raw",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw history string (legacy format from Export_HistoryBuilder). Excel: AZ (52), Access: Value52 (Memo field). Sessions separated by '||'. Normalized history in history app.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when record was created in Django.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated in Django.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kartei Record",
                "verbose_name_plural": "Kartei Records",
                "db_table": "karteien_record",
                "ordering": ["year", "family_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["year", "status"], name="idx_kartei_year_status"
                    ),
                    models.Index(
                        fields=["family_id", "year"], name="idx_kartei_family_year"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "id"), name="unique_kartei_year_id"
                    )
                ],
            },
        ),
    ]
