# Generated by Django 5.2.9 on 2025-12-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_discount_recorddiscount_familydiscount"),
        ("karteien", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="karteirecord",
            name="price1_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to catalog PriceOption for subject1.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kartei_records_price1",
                to="catalog.priceoption",
                verbose_name="Preis 1 (Ref)",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="price2_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to catalog PriceOption for subject2.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kartei_records_price2",
                to="catalog.priceoption",
                verbose_name="Preis 2 (Ref)",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="start_month_1",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Starting month for billing in 1st semester (1-6). Months before this are 0.00.",
                verbose_name="Startmonat 1. HJ",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="start_month_2",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Starting month for billing in 2nd semester (7-12). Months before this are 0.00.",
                verbose_name="Startmonat 2. HJ",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="subject1_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to catalog Subject for subject1 (1st semester).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kartei_records_subject1",
                to="catalog.subject",
                verbose_name="Fach 1 (Ref)",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="subject2_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to catalog Subject for subject2 (2nd semester).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kartei_records_subject2",
                to="catalog.subject",
                verbose_name="Fach 2 (Ref)",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="teacher1_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to catalog Teacher for subject1.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kartei_records_teacher1",
                to="catalog.teacher",
                verbose_name="Lehrer 1 (Ref)",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="teacher2_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to catalog Teacher for subject2.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kartei_records_teacher2",
                to="catalog.teacher",
                verbose_name="Lehrer 2 (Ref)",
            ),
        ),
    ]
