# Generated by Django 5.2.9 on 2025-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karteien", "0002_add_catalog_refs_and_start_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="karteirecord",
            name="base_amounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Base amounts before discounts. Keys: month_1..month_12, Values: Decimal strings.",
                verbose_name="Basisbeträge",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="discounts_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, no discounts are applied to this record.",
                verbose_name="Rabatte deaktiviert",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="hours_amounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Academic hours per month for Individual/NH subjects. Keys: month_1..month_12.",
                verbose_name="Stunden pro Monat",
            ),
        ),
        migrations.AddField(
            model_name="karteirecord",
            name="months_mode",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy (manual)"),
                    ("AUTO", "Automatic"),
                    ("OVERRIDE", "Override"),
                ],
                default="LEGACY",
                help_text="LEGACY: manual entry, AUTO: automatic calculation, OVERRIDE: emergency override.",
                max_length=10,
                verbose_name="Abrechnungsmodus",
            ),
        ),
    ]
