# Generated by Django 5.2.9 on 2026-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karteien", "0005_add_discounts_disabled_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="karteirecord",
            name="contract_terminated_from_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Month (1-12) from which the contract is terminated. Months >= this value should be zeroed. Only set if is_contract_terminated=True.",
                null=True,
                verbose_name="Kündigung ab Monat",
            ),
        ),
    ]
