# Generated by Django 5.2.9 on 2026-01-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karteien", "0008_add_months_csv_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="karteirecord",
            name="legacy_base_amounts_enabled",
            field=models.BooleanField(
                default=False,
                help_text="True if discounts were applied to this LEGACY record using saved month values as base. Enables breakdown display for LEGACY mode. Reset when converting to AUTO mode.",
                verbose_name="Legacy-Basis aktiv",
            ),
        ),
    ]
