# Generated by Django 5.2.9 on 2026-02-11 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karteien", "0009_legacy_base_amounts_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractStatusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from_month",
                    models.PositiveSmallIntegerField(
                        help_text="Month (1-12) from which this contract status takes effect.",
                        verbose_name="Gültig ab Monat",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktiv"),
                            ("PAUSED", "Pausiert"),
                            ("TERMINATED", "Gekündigt"),
                        ],
                        help_text="Contract status: ACTIVE, PAUSED, or TERMINATED.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Geändert am"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Kommentar"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_status_entries",
                        to="karteien.karteirecord",
                        verbose_name="Kartei Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Status Entry",
                "verbose_name_plural": "Contract Status Entries",
                "db_table": "karteien_contract_status_entry",
                "ordering": ["effective_from_month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "effective_from_month"),
                        name="unique_contract_status_record_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_from_month__gte", 1),
                            ("effective_from_month__lte", 12),
                        ),
                        name="contract_status_month_1_12",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractTypeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from_month",
                    models.PositiveSmallIntegerField(
                        help_text="Month (1-12) from which this contract type takes effect.",
                        verbose_name="Gültig ab Monat",
                    ),
                ),
                (
                    "is_monthly",
                    models.BooleanField(
                        help_text="True = monthly contract (O/V), False = yearly contract.",
                        verbose_name="Monatsvertrag",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Geändert am"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Kommentar"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_type_entries",
                        to="karteien.karteirecord",
                        verbose_name="Kartei Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Type Entry",
                "verbose_name_plural": "Contract Type Entries",
                "db_table": "karteien_contract_type_entry",
                "ordering": ["effective_from_month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "effective_from_month"),
                        name="unique_contract_type_record_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_from_month__gte", 1),
                            ("effective_from_month__lte", 12),
                        ),
                        name="contract_type_month_1_12",
                    ),
                ],
            },
        ),
    ]
