# Generated by Django 5.2.9 on 2026-01-27 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyIdReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family_id",
                    models.CharField(
                        db_index=True,
                        help_text='Reserved FamilyID in format "1. <number>"',
                        max_length=50,
                        unique=True,
                        verbose_name="Family ID",
                    ),
                ),
                (
                    "reserved_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the reservation was created",
                        verbose_name="Reserved At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this reservation has been used to create a family",
                        verbose_name="Is Used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the reservation was used to create a family",
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note about this reservation",
                        max_length=200,
                        verbose_name="Note",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the reservation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="familyid_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reserved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "FamilyID Reservation",
                "verbose_name_plural": "FamilyID Reservations",
                "ordering": ["-reserved_at"],
                "indexes": [
                    models.Index(
                        fields=["is_used", "reserved_at"],
                        name="familyid_res_active_idx",
                    )
                ],
            },
        ),
    ]
