# Generated by Django 5.2.9 on 2025-12-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karteien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(db_index=True, help_text='When the event occurred. Parsed from history date or set at creation.')),
                ('event_type', models.CharField(choices=[('CHANGE', 'Field Change'), ('CREATE', 'Record Created'), ('APPROVE', 'Approved'), ('DECLINE', 'Declined'), ('IMPORT', 'Imported'), ('RUCK', 'Retroactive Change')], db_index=True, default='CHANGE', help_text='Type of event: CHANGE, CREATE, APPROVE, DECLINE, IMPORT, RUCK.', max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON structure of changes: {"field_name": {"old": <value>, "new": <value>}, ...}')),
                ('comment', models.TextField(blank=True, default='', help_text='User comment for this change session (parsed from /@...@/).')),
                ('raw_history_fragment', models.TextField(blank=True, default='', help_text='Original history string segment from AZ/Value52. Stored for debugging and backward compatibility.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(help_text='The KarteiRecord this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='karteien.karteirecord')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the change. Null for imported/legacy events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Event',
                'verbose_name_plural': 'History Events',
                'db_table': 'history_event',
                'ordering': ['-event_time', '-id'],
                'indexes': [models.Index(fields=['record', 'event_time'], name='history_eve_record__aa057f_idx'), models.Index(fields=['event_type', 'event_time'], name='history_eve_event_t_f5fcab_idx')],
            },
        ),
    ]
