# Generated by Django 5.2.9 for KindEltern Web
# Initial migration for approvals app - PendingChange, DeclinedChange, SuperadminState

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('karteien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='Auto-generated primary key (not the same as KarteiRecord.id).',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'snapshot',
                    models.JSONField(
                        default=dict,
                        help_text="JSON snapshot of proposed field values. Contains all tracked "
                                  "fields from KarteiRecord. Format: {'field_name': value, ...}. "
                                  "See DOMAIN_MODEL.md Section 4 for tracked fields list.",
                    ),
                ),
                (
                    'is_processed',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='True if this pending change has been processed (approved/declined). '
                                  'Processed records are kept for audit trail.',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Timestamp when pending change was first created.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Timestamp of last update (e.g., Admin made further edits).',
                    ),
                ),
                (
                    'record',
                    models.OneToOneField(
                        help_text='Reference to the original KarteiRecord. OneToOne ensures only '
                                  'one pending change per record at a time.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pending_change',
                        to='karteien.karteirecord',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Pending Change',
                'verbose_name_plural': 'Pending Changes',
                'db_table': 'approvals_pending_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeclinedChange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='Auto-generated primary key.',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'snapshot',
                    models.JSONField(
                        default=dict,
                        help_text='JSON snapshot of declined field values. Same format as '
                                  'PendingChange.snapshot. Preserved for audit trail.',
                    ),
                ),
                (
                    'decline_reason',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Reason provided by Superadmin for declining the change. '
                                  'May include instructions for Admin on how to fix the data.',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Timestamp when change was declined.',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Timestamp of last update.',
                    ),
                ),
                (
                    'declined_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Superadmin user who declined the change.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='declined_changes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'record',
                    models.ForeignKey(
                        help_text='Reference to the KarteiRecord that had changes declined. '
                                  'ForeignKey (not OneToOne) allows multiple decline events per record.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='declined_changes',
                        to='karteien.karteirecord',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Declined Change',
                'verbose_name_plural': 'Declined Changes',
                'db_table': 'approvals_declined_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuperadminState',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='Auto-generated primary key.',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'last_seen_id',
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Last seen record ID. Records with ID > this value "
                                  "are considered 'new' in NeuList view.",
                    ),
                ),
                (
                    'last_seen_date',
                    models.DateTimeField(
                        blank=True,
                        help_text="Alternative: last seen date. Records created after this "
                                  "are considered 'new'. Optional, ID-based is primary.",
                        null=True,
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Timestamp of last state update.',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        help_text='Superadmin user this state belongs to.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='superadmin_state',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Superadmin State',
                'verbose_name_plural': 'Superadmin States',
                'db_table': 'approvals_superadmin_state',
            },
        ),
        migrations.AddIndex(
            model_name='pendingchange',
            index=models.Index(
                fields=['is_processed', 'created_at'],
                name='idx_pending_processed_created',
            ),
        ),
        migrations.AddIndex(
            model_name='declinedchange',
            index=models.Index(
                fields=['record', 'created_at'],
                name='idx_declined_record_created',
            ),
        ),
    ]
