# Generated by Django 5.2.9 on 2026-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingchange",
            name="admin_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comment provided by Admin when making a risky change. Required for RISKY changes. Shown to Superadmin in War/Ist view.",
            ),
        ),
    ]
