# Generated by Django 5.2.9 on 2026-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0003_superadminstate_last_seen_by_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="superadminstate",
            name="last_seen_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Last seen record ID (legacy/fallback). Records with ID > this value are considered 'new' in NeuList view. For proper per-year tracking, see last_seen_by_year.",
            ),
        ),
    ]
