# Generated by Django 5.2.9 on 2025-12-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название предмета",
                        max_length=200,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активен ли предмет",
                        verbose_name="Aktiv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия преподавателя",
                        max_length=100,
                        verbose_name="Nachname",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя преподавателя",
                        max_length=100,
                        verbose_name="Vorname",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активен ли преподаватель",
                        verbose_name="Aktiv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("last_name", "first_name"), name="unique_teacher_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Учебный год (например, 2024, 2025)",
                        verbose_name="Jahr",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активно ли назначение",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Предмет",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="catalog.subject",
                        verbose_name="Fach",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Преподаватель",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="catalog.teacher",
                        verbose_name="Lehrer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teaching Assignment",
                "verbose_name_plural": "Teaching Assignments",
                "ordering": ["-year", "subject__name", "teacher__last_name"],
                "indexes": [
                    models.Index(fields=["year", "subject"], name="idx_year_subject"),
                    models.Index(fields=["year", "teacher"], name="idx_year_teacher"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "subject", "teacher"),
                        name="unique_year_subject_teacher",
                    )
                ],
            },
        ),
    ]
