# Generated by Django 5.2.9 on 2025-12-17 16:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Учебный год (например, 2024, 2025)",
                        verbose_name="Jahr",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма (€)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Betrag",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Комментарий (почему такая цена)",
                        verbose_name="Kommentar",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активна ли эта цена",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Предмет",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_options",
                        to="catalog.subject",
                        verbose_name="Fach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Option",
                "verbose_name_plural": "Price Options",
                "ordering": ["-year", "subject__name", "amount"],
                "indexes": [
                    models.Index(
                        fields=["year", "subject"], name="idx_price_year_subject"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "subject", "amount", "comment"),
                        name="unique_year_subject_amount_comment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", Decimal("0.00"))),
                        name="price_amount_non_negative",
                    ),
                ],
            },
        ),
    ]
