# Generated by Django 5.2.9 on 2025-12-17 16:59

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_priceoption"),
        ("karteien", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PERCENT", "Prozent (%)"), ("FIXED", "Fest (€)")],
                        default="PERCENT",
                        help_text="Тип скидки: процентная или фиксированная",
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Для PERCENT: 0.00-0.99 (например 0.25 = 25%). Для FIXED: сумма в EUR.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Wert",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Описание скидки",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активна ли скидка",
                        verbose_name="Aktiv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ["kind", "-value"],
            },
        ),
        migrations.CreateModel(
            name="RecordDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Начальный месяц (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Von Monat",
                    ),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Конечный месяц (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Bis Monat",
                    ),
                ),
                (
                    "months",
                    models.JSONField(
                        blank=True,
                        help_text="Если задано [1,2,3], диапазон start_month..end_month игнорируется",
                        null=True,
                        validators=[apps.catalog.models.validate_months_list],
                        verbose_name="Monate (Liste)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        help_text="Применяемая скидка",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.discount",
                        verbose_name="Rabatt",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        help_text="Запись, к которой применяется скидка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_discounts",
                        to="karteien.karteirecord",
                        verbose_name="Kartei-Eintrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record Discount",
                "verbose_name_plural": "Record Discounts",
                "ordering": ["-record__year", "record__pkid", "start_month"],
            },
        ),
        migrations.CreateModel(
            name="FamilyDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Начальный месяц (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Von Monat",
                    ),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Конечный месяц (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Bis Monat",
                    ),
                ),
                (
                    "months",
                    models.JSONField(
                        blank=True,
                        help_text="Если задано [1,2,3], диапазон start_month..end_month игнорируется",
                        null=True,
                        validators=[apps.catalog.models.validate_months_list],
                        verbose_name="Monate (Liste)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Учебный год", verbose_name="Jahr"
                    ),
                ),
                (
                    "family_id",
                    models.CharField(
                        db_index=True,
                        help_text="Идентификатор семьи (как в KarteiRecord.family_id)",
                        max_length=50,
                        verbose_name="FamilyID",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        help_text="Применяемая скидка",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.discount",
                        verbose_name="Rabatt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Discount",
                "verbose_name_plural": "Family Discounts",
                "ordering": ["-year", "family_id", "start_month"],
                "indexes": [
                    models.Index(
                        fields=["year", "family_id"],
                        name="idx_family_discount_year_fam",
                    )
                ],
            },
        ),
    ]
