# Generated by Django 5.2.9 on 2026-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_discount_recorddiscount_familydiscount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemesterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Календарный год", unique=True, verbose_name="Jahr"
                    ),
                ),
                (
                    "last_month_sem1",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Последний месяц семестра 1 (1-11)",
                        verbose_name="Letzter Monat Semester 1",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Semester Config",
                "verbose_name_plural": "Semester Configs",
                "ordering": ["-year"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("last_month_sem1__gte", 1), ("last_month_sem1__lte", 11)
                        ),
                        name="semester_boundary_range_1_to_11",
                    )
                ],
            },
        ),
    ]
