# Generated by Django 5.2.9 on 2026-02-11 20:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_semester_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Календарный год", verbose_name="Jahr"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Название категории ("Русский", "Танцы" и т.д.)',
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GROUP", "Gruppenunterricht"),
                            ("INDIVIDUAL", "Einzelunterricht"),
                        ],
                        help_text="Тип категории: групповой или индивидуальный",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "yearly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ставка €/UE (45 мин) для годичного контракта",
                        max_digits=10,
                        verbose_name="Jahresvertrag €/UE",
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ставка €/UE (45 мин) для месячного контракта",
                        max_digits=10,
                        verbose_name="Monatsvertrag €/UE",
                    ),
                ),
                (
                    "group_threshold",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Порог малокомплектности (только для GROUP)",
                        verbose_name="Schwellenwert Kleingruppe",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активна ли категория (мягкое удаление)",
                        verbose_name="Aktiv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Category",
                "verbose_name_plural": "Subject Categories",
                "ordering": ["-year", "name"],
                "indexes": [
                    models.Index(
                        fields=["year", "kind"], name="idx_category_year_kind"
                    ),
                    models.Index(
                        fields=["year", "is_active"], name="idx_category_year_active"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "name"), name="unique_category_year_name"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("yearly_rate__gte", Decimal("0.00"))),
                        name="category_yearly_rate_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("monthly_rate__gte", Decimal("0.00"))),
                        name="category_monthly_rate_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("group_threshold__gte", 1)),
                        name="category_group_threshold_min_1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectCategoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        help_text="Денормализовано из category.year",
                        verbose_name="Jahr",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория дисциплины",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="catalog.subjectcategory",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Предмет",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_links",
                        to="catalog.subject",
                        verbose_name="Fach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject ↔ Category Link",
                "verbose_name_plural": "Subject ↔ Category Links",
                "ordering": ["-year", "category__name", "subject__name"],
                "indexes": [
                    models.Index(
                        fields=["year", "category"], name="idx_link_year_category"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject", "year"), name="unique_subject_year_category"
                    )
                ],
            },
        ),
    ]
