# Generated by Django 5.2.9 on 2026-02-11 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_add_subject_category_and_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Учебный год", verbose_name="Jahr"
                    ),
                ),
                (
                    "auto_scaling_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Включён ли автоскейлинг малокомплектных",
                        verbose_name="Auto-Scaling",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Мягкая деактивация группы",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория (только GROUP)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="catalog.subjectcategory",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Предмет",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discipline_groups",
                        to="catalog.subject",
                        verbose_name="Fach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discipline Group",
                "verbose_name_plural": "Discipline Groups",
                "ordering": ["-year", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="DurationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from_month",
                    models.PositiveSmallIntegerField(
                        help_text="Действует с месяца (1-12)", verbose_name="Ab Monat"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        help_text="Продолжительность в минутах",
                        verbose_name="Dauer (Min.)",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда изменено",
                        verbose_name="Geändert am",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Комментарий",
                        verbose_name="Kommentar",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="Кем изменено",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Группа",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration_entries",
                        to="catalog.disciplinegroup",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duration Entry",
                "verbose_name_plural": "Duration Entries",
                "ordering": ["effective_from_month"],
            },
        ),
        migrations.CreateModel(
            name="GroupSizeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from_month",
                    models.PositiveSmallIntegerField(
                        help_text="Действует с месяца (1-12)", verbose_name="Ab Monat"
                    ),
                ),
                (
                    "manual_size",
                    models.PositiveSmallIntegerField(
                        help_text="Ручной размер группы", verbose_name="Manuelle Größe"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда изменено",
                        verbose_name="Geändert am",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Комментарий",
                        verbose_name="Kommentar",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="Кем изменено",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Группа",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_entries",
                        to="catalog.disciplinegroup",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Size Entry",
                "verbose_name_plural": "Group Size Entries",
                "ordering": ["effective_from_month"],
            },
        ),
        migrations.AddIndex(
            model_name="disciplinegroup",
            index=models.Index(
                fields=["year", "category"], name="idx_group_year_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="disciplinegroup",
            constraint=models.UniqueConstraint(
                fields=("subject", "year"), name="unique_discipline_group_subject_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="durationentry",
            constraint=models.UniqueConstraint(
                fields=("group", "effective_from_month"),
                name="unique_duration_group_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="durationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from_month__gte", 1), ("effective_from_month__lte", 12)
                ),
                name="duration_month_range_1_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="durationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gte", 1)),
                name="duration_minutes_min_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsizeentry",
            constraint=models.UniqueConstraint(
                fields=("group", "effective_from_month"), name="unique_size_group_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsizeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from_month__gte", 1), ("effective_from_month__lte", 12)
                ),
                name="size_month_range_1_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsizeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("manual_size__gte", 1)), name="manual_size_min_1"
            ),
        ),
    ]
